import vertica_python

conn_info = {'host': '127.0.0.1',
             'port': 5433,
             'user': 'olib92',
             'password': 'Transformer2',
             'database': 'xformer',
             # autogenerated session label by default,
             'session_label': 'some_label',
             # 10 minutes timeout on queries
             'read_timeout': 6000,
             # default throw error on invalid UTF-8 results
             'unicode_error': 'strict',
             # SSL is disabled by default
             'ssl': False,
             # using server-side prepared statements is disabled by default
             'use_prepared_statements': False,
             # connection timeout is not enabled by default
             # 'connection_timeout': 5
             }
connection = vertica_python.connect(**conn_info)
cur = connection.cursor()
